### PR TITLE
Typescript declaration file

### PR DESCRIPTION
**Pull request by jimmythecoder**
I wrote a Typescript typings declaration file for using AutoNumeric as an ambient JS include in a TypeScript project. It contains most methods and properties, but not all. Some of the documentation isn't clear but it will be fine for 90% of projects.

### CODE REVIEW

**Comment by jimmythecoder** [comment]
Hi! Thanks for the review, Typescript does not use or understand JSdoc other than intellisense hints. An ambient .d.ts is always required to consume a 3rd party lib. 

I feel that typescript is the most useful thing in front end since jQuery so I highly recommend supporting it :) I’m happy to go through your comments and make changes, AutoNumeric is a large lib so I havnt defined everything in there yet and as your comments pointed out some things are amiss. Some JavaScript statements are also highly dynamic and take some thinking in order to type correctly I may have simplified it a bit to get my own code working such as multiple constructors or multiple return types with generics takes a deep understand of the code itself not always visible from the docs so your welcome to correct anything in there :) 

I’m sure as frameworks grow and become more widely used especially angular these ambient ts files are super helpful and provide the best programmers guidance on how to use the api, very nice in vscode with intellisense for method names params and returns. 

Cheers!

**Comment by AlexandreBonneau** [comment]
Have you ever tried automated tools like [tsd-jsdoc](https://github.com/englercj/tsd-jsdoc) or [jsdoc-to-typescript-declaration](https://github.com/brettle/jsdoc-to-typescript-declaration) before?
What are you thoughts on those?
Couldn't they be used to automate the tasks of creating such file?

I'm open to add the definition file if it can improve the dev life, but if we were to have such file, then it **needs** to be always up-to-date with the codebase since we strive to deliver only top quality code (we had an old d.ts file before, be we scrapped it since it was largely outdated, and nobody complained about it!).

That means that having to do it by hand is a no-go since it adds even more steps to do when publishing a new version (ie. changing the source code header, package.json, changelog, readme.md, documentation component on the autonumeric.org, etc.), that's why I'm asking about an automated way to generate it.

I recognize your efforts *and* the usefulness of that file, the problem however as I see it is maintaining it.

**Comment by chadbengen** [comment]
FWIW i created a more comprehensive [definition file here](https://gist.github.com/chadbengen/7a3b696789b4af73b6be9ee4ccdbf05d) .

**Comment by AlexandreBonneau** [comment]
Thanks @chadbengen !
Is there any way to merge both your great works together @jimmythecoder?

**Comment by AlexandreBonneau** [comment]
Hey @jimmythecoder, @chadbengen, is a merge something you would be willing to do?

**Comment by chadbengen** [comment]
@AlexandreBonneau I am not able to put in any time to do that personally.  If @jimmythecoder wants to merge the files he has my blessing. If i make any changes or updates i'll be sure to post something.

**Comment by mseele** [comment]
Any news on this?

**Comment by AlexandreBonneau** [comment]
@mseele #661 is on the way, which merge work from this PR

**Comment by AlexandreBonneau** [comment]
The updated definition file has been merged in #661, based on your work.
Thanks @jimmythecoder and @chadbengen !

**Pull request closed without merging**
