### PR TITLE
tests: test Node.js 10

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
Well, upath again.

**Comment by AlexandreBonneau** [comment]
The node 10 job is failing on Travis while node 6 and 8 are running fine.
As is, I cannot merge the change before making sure everything is green.

I see in the [log](https://travis-ci.org/autoNumeric/autoNumeric/jobs/428018703) that yarn version `1.3.2` is used (and that's very old ; I run `1.9.4` here)), so that could be the cause, but I'm not sure why it installs a such outdated version (perhaps related to [this travis issue](https://github.com/travis-ci/travis-ci/issues/7566)).
Any ideas how to fix that?

**Comment by DanielRuf** [comment]
```
FAILED TESTS:
  The AutoNumeric object
    initialization methods
      ✖ should correctly initialize the AutoNumeric element when the `formatOnPageLoad` option is set
        Firefox 61.0.0 (Mac OS X 10.13.0)
      Expected '12234678.321' to equal '$12,234,678.32'.
      <Jasmine>
      ./test/unit/autoNumeric.spec.js/</</<@webpack://autonumeric/test/unit/autoNumeric.spec.js:1150:12 <- tests.webpack.js:9:705409
      <Jasmine>

  Initialization calls
    Initialize a single AutoNumeric object
      ✖ should fail to init when the default value is outside of the min and max limits
        PhantomJS 2.1.1 (Mac OS X 0.0.0)
      TypeError: undefined is not an object (evaluating 'aNInput.remove') in tests.webpack.js (line 9)
      webpack://autonumeric/webpack/universalModuleDefinition:1:0 <- tests.webpack.js:9:1481375
      <Jasmine>

  autoNumeric options and `options.*` methods
    `options.*` methods
      ✖ should correctly update the `decimalPlacesShownOnFocus` option
        Firefox 61.0.0 (Mac OS X 10.13.0)
      Expected '2.222,12 €' to equal '2.222,1235 €'.
      <Jasmine>
      ./test/unit/autoNumeric.spec.js/</</<@webpack://autonumeric/test/unit/autoNumeric.spec.js:1483:12 <- tests.webpack.js:9:734042
      <Jasmine>

  Instantiated autoNumeric functions
    `selectInteger`
      ✖ should select only the decimal part
        Firefox 61.0.0 (Mac OS X 10.13.0)
      Expected '12.266,123 €' to equal '12.266,123457 €'.
      <Jasmine>
      ./test/unit/autoNumeric.spec.js/</</<@webpack://autonumeric/test/unit/autoNumeric.spec.js:5157:12 <- tests.webpack.js:9:990807
      <Jasmine>

  The AutoNumeric event lifecycle
    ✖ should send the 'autoNumeric:formatted' event when formatting is done
      Firefox 61.0.0 (Mac OS X 10.13.0)
    Expected spy formattedEvent to have been called 6 times. It was called 5 times.
    <Jasmine>
    ./test/unit/autoNumeric.spec.js/</<@webpack://autonumeric/test/unit/autoNumeric.spec.js:8420:8 <- tests.webpack.js:9:1305434
    <Jasmine>

```

**Comment by DanielRuf** [comment]
> I see in the [log](https://travis-ci.org/autoNumeric/autoNumeric/jobs/428018703) that yarn version `1.3.2` is used (and that's very old ; I run `1.9.4` here)), so that could be the cause, but I'm not sure why it installs a such outdated version (perhaps related to [this travis issue](https://github.com/travis-ci/travis-ci/issues/7566)).
> Any ideas how to fix that?

No, the cause is upath ;-)
See `yarn why upath`.

**Comment by DanielRuf** [comment]
Regarding https://github.com/autoNumeric/autoNumeric/pull/605#issuecomment-420917989, I'm on a macBook with German localization and German as language in the browsers (by default).

**Comment by AlexandreBonneau** [comment]
Please open a new issue about [that](https://github.com/autoNumeric/autoNumeric/pull/605#issuecomment-420917989) matter then. AutoNumeric needs to work correctly for all languages.

About this PR, everything looks fine...merging!

**Pull request merged**
