### PR TITLE
fix: correct invalid JS imports

### PR DESCRIPTION
**Pull request by mseele**
closes https://github.com/autoNumeric/autoNumeric/issues/752

### CODE REVIEW

**Comment by MIreland** [comment]
This fixed my issues with `vite`- any chance we could get this in soon? @AlexandreBonneau  @BobKnothe

**Comment by lfdantoni** [comment]
Hello, this fixed my issue with vite as well, could it be merged soon please?

**Comment by danieldiekmeier** [comment]
Thanks, this is incredibly helpful! It allowed us to use AutoNumeric with Vite. For anyone else who's eagerly waiting for this to be released: You can directly install mseele's fork with:

```sh
npm i https://github.com/mseele/autoNumeric\#f07f59547aee71efc732fedcd6b3403631608694
yarn add https://github.com/mseele/autoNumeric\#f07f59547aee71efc732fedcd6b3403631608694
```

Leading to this in your `package.json`:

```diff
  "@splidejs/splide": "^4.1.4",
+ "autonumeric": "https://github.com/mseele/autoNumeric#f07f59547aee71efc732fedcd6b3403631608694",
  "copy-text-to-clipboard": "^3.0.1",
```

**Comment by damicolucas** [comment]
Hello!! This also fixed my issue with vite, could it be merged soon please?

**Review by eneaaliko0 — APPROVED** [review]
Hello all, this is the solution to this bug, thank you very much [mseele](https://github.com/mseele)! Please merge as soon as possible!

**Pull request merged**
